name: terraform-help

on: 
  issue_comment: 
    types: [created]

jobs:
  show-help:
    # Only run for comments starting with "terraform help" in a pull request.
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'terraform help')

    name: Terraform Show Help
    runs-on: ubuntu-latest

    steps:
      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch

      - name: Set latest commit status as pending
        uses: myrotvorets/set-commit-status-action@master
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending

      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      # - name: Set latest commit status as ${{ job.status }}
      #   uses: myrotvorets/set-commit-status-action@master
      #   if: always()
      #   with:
      #     sha: ${{ steps.comment-branch.outputs.head_sha }}
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     status: ${{ job.status }}

      - name: Add comment to PR
        uses: actions/github-script@v6
        if: always()
        with:
          script: |
            const name = '${{ github.workflow   }}';
            const url = '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}';
            const success = '${{ job.status }}' === 'success';
            const body = `${name}: ${success ? 'succeeded ✅' : 'failed ❌'}\n${url}`;

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })

      # - name: Show Help
      #   env:
      #     COMMENTS_URL: ${{ steps.load-pr.outputs.comments_url }}
      #   run: |
      #     set -eu
      #     echo "Sending help text to: $COMMENTS_URL"
      #     helpPayload=$(cat .github/workflows/tf-help.md | jq -R --slurp '{body: .}')

      #     resp=$(echo $helpPayload | curl -sSf \
      #       --url $COMMENTS_URL \
      #       --data @- \
      #       --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
      #       --header 'content-type: application/json')
      #     echo "Adding comment returned: $resp"